### ISSUE TITLE
Minimum Essential Metadata changes

### ISSUE THREAD

**Issue by cchipman6** [niemopen/niem-model#40]
The DoD Minimum Essential Metadata were updated by DoD Metadata Guidance issued by the DoD Chief Digital and Artificial Intelligence Officer in March 2023. The attached spreadsheet reflects the changes, which were discussed and approved during the 9 Aug MilOps Subcommittee meeting. 
[MEM Update_11Jul2023.xlsx](https://github.com/niemopen/niem-model/files/12455606/MEM.Update_11Jul2023.xlsx)

**Comment by cdmgtri** [comment]
Made the following additional changes to support NDR conformance rules and model consistency:

- Updated the **definition of mo:MinimumEssentialMetadataType** to follow the NDR's standard opening phrase for metadata types: 
  - "A data type for metadata about a data resource that represents the DoD's minimum essential set."  
- Selected "Resource" as the class term for properties in the type to match other existing resource properties:
  - Renamed mo:DataItemCreateDateTime as **mo:ResourceCreateDateTime**
  - Renamed mo:DataResourceCustodian as **mo:ResourceCustodian** 
- Renamed mo:ResourceCreateDateTime as **mo:ResourceCreateDate** because either a date or a date and time is allowed.

**Comment by cdmgtri** [comment]
Also added the codes in the change request spreadsheet marked with code "map" (Type-Has-Property tab).

**Comment by cdmgtri** [comment]
Merged into the dev branch for 6.0.
