### ISSUE TITLE
Version 6.0 Internal Review - NCIC codes

### ISSUE THREAD

**Issue by aprilm99** [niemopen/niem-model#87]
I reviewed the NCIC codes especially and found a few that needed to be added, updated or deleted. I am attaching the facet spreadsheet.  

I also noticed a few descriptions with double spaces but did not include them in the spreadsheet.

[niem-facet-6.0-update.xlsx](https://github.com/niemopen/niem-model/files/12872093/niem-facet-6.0-update.xlsx)

**Comment by Shunbah** [comment]
Jim Cabral volunteered to work this in today's NTAC-TSC.  The TSC commented that xsd/codes/ncic.xsd schema and the docs/niem-6.0-codes.xlsx files need to be updated.  There is one definition that is blank. That one needs to keep the existing definition to pass validation. Contact April Mitchell with any questions.

**Comment by mikehulme** [comment]
I can help with this as well or instead of Jim. I am familiar with this topic.

**Comment by cabralje** [comment]
Mike,

I would appreciate the help. Can you generate the pull request?

__
Jim Cabral
502-640-4970

________________________________

**Comment by mikehulme** [comment]
Yes

**Comment by albeach** [comment]
Jim & Mike,Once the pull request is generated I can merge with the dev branch if there are no conflicts. Let me know if there are any additional steps for code review.v/r,AubreyOn Oct 17, 2023, at 11:26 AM, Jim Cabral ***@***.***> wrote:﻿
Mike,



I would appreciate the help. Can you generate the pull request?



__

Jim Cabral

502-640-4970



________________________________

From: Mike Hulme ***@***.***>

Sent: Tuesday, October 17, 2023 10:52 AM

To: niemopen/niem-model

Cc: Jim Cabral; Assign

Subject: Re: [niemopen/niem-model] Version 6.0 Internal Review - NCIC codes (Issue #87)





I can help with this as well or instead of Jim. I am familiar with this topic.

**Comment by mikehulme** [comment]
Completed and emailed the ncic codes XML schema and spreadsheet to Scott Renner for incorporation into the release. 
@aprilm99 - I attached the facets spreadsheet with two added columns stating the action taken.
[niem-facet-6.0-update-applied.xlsx](https://github.com/niemopen/niem-model/files/13127649/niem-facet-6.0-update-applied.xlsx)

**Comment by iamdrscott** [comment]
Completed by https://github.com/niemopen/niem-model/commit/8533fb1ef0b86b87ec98e03c7071ee8fab6bf409
